// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "jni.h"
#include "dartjni.h"

thread_local JNIEnv *jniEnv;
JniContext *jni;

JniContext *(*context_getter)(void);
JNIEnv *(*env_getter)(void);

void setJniGetters(JniContext *(*cg)(void),
        JNIEnv *(*eg)(void)) {
    context_getter = cg;
    env_getter = eg;
}

// JavaExample
jclass _c_JavaExample = NULL;

jmethodID _m_JavaExample__ctor = NULL;
FFI_PLUGIN_EXPORT
JniResult JavaExample__ctor() {
    load_env();
        load_class_global_ref(&_c_JavaExample, "JavaExample");
    if (_c_JavaExample == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_method(_c_JavaExample,
      &_m_JavaExample__ctor, "<init>", "()V");
    if (_m_JavaExample__ctor == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    jobject _result = (*jniEnv)->NewObject(jniEnv, _c_JavaExample, _m_JavaExample__ctor);
    return to_global_ref_result(_result);
}

jmethodID _m_JavaExample__sum = NULL;
FFI_PLUGIN_EXPORT
JniResult JavaExample__sum(int32_t a,int32_t b) {
    load_env();
        load_class_global_ref(&_c_JavaExample, "JavaExample");
    if (_c_JavaExample == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    load_static_method(_c_JavaExample,
      &_m_JavaExample__sum, "sum", "(II)I");
    if (_m_JavaExample__sum == NULL) return (JniResult){.value = {.j = 0}, .exception = check_exception()};
    int32_t _result = (*jniEnv)->CallStaticIntMethod(jniEnv, _c_JavaExample, _m_JavaExample__sum, a, b);
    return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}

