name: dart_ffi
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.5

dependencies:
  ffi: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  name: SwiftBindings
  language: objc
  output: 'lib/swift_bindings.dart'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - 'SwiftClass'
    module:
      'SwiftClass': 'swift_module'
  headers:
    entry-points:
      - 'swift/swift.h'
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api