name: dart_ffi
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  jni: ^0.5.0
  path: ^1.8.0

dev_dependencies:
  jnigen: ^0.5.0
  lints: ^2.0.0
  test: ^1.21.0
