name: dart_ffi
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.5

dependencies:
  ffi: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
