// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: file_names
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_cast
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_shown_name

import "dart:isolate" show ReceivePort;
import "dart:ffi" as ffi;
import "package:jni/internal_helpers_for_jnigen.dart";
import "package:jni/jni.dart" as jni;

// Auto-generated initialization code.

final ffi.Pointer<T> Function<T extends ffi.NativeType>(String sym) jniLookup =
    ProtectedJniExtensions.initGeneratedLibrary("java");

/// from: JavaExample
class JavaExample extends jni.JObject {
  @override
  late final jni.JObjType<JavaExample> $type = type;

  JavaExample.fromRef(
    jni.JObjectPtr ref,
  ) : super.fromRef(ref);

  /// The type which includes information such as the signature of this class.
  static const type = $JavaExampleType();
  static final _ctor = jniLookup<ffi.NativeFunction<jni.JniResult Function()>>("JavaExample__ctor")
      .asFunction<jni.JniResult Function()>();

  /// from: public void <init>()
  /// The returned object must be deleted after use, by calling the `delete` method.
  factory JavaExample() {
    return JavaExample.fromRef(_ctor().object);
  }

  static final _sum = jniLookup<ffi.NativeFunction<jni.JniResult Function(ffi.Int32, ffi.Int32)>>(
          "JavaExample__sum")
      .asFunction<jni.JniResult Function(int, int)>();

  /// from: static public int sum(int a, int b)
  static int sum(
    int a,
    int b,
  ) {
    return _sum(a, b).integer;
  }
}

class $JavaExampleType extends jni.JObjType<JavaExample> {
  const $JavaExampleType();

  @override
  String get signature => r"LJavaExample;";

  @override
  JavaExample fromRef(jni.JObjectPtr ref) => JavaExample.fromRef(ref);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($JavaExampleType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($JavaExampleType) && other is $JavaExampleType;
  }
}
